use_frameworks!
platform :ios, '8.0'
inhibit_all_warnings!

target 'LYImagePicker_Example' do
	pod 'LYImagePicker', :path => '../'

	target 'LYImagePicker_Tests' do
		inherit! :search_paths

		pod 'Quick', '~> 1.0.0'
		pod 'Nimble', '~> 5.1.1'
	end
end
