use_frameworks!
platform :ios, '10.0'
inhibit_all_warnings!

project './LYImagePicker.xcodeproj'

target 'LYImagePicker_Example' do
	pod 'LYImagePicker', :path => '../'
	
	pod 'BlocksKit'
	pod 'FLAnimatedImage'
end
